sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - PIP=pip

matrix:
  include:
    - os: linux
      python: 3.7
      dist: xenial
      sudo: true
    - os: linux
      python: 3.8
      dist: xenial
      sudo: true
    - os: osx
      language: generic
      env:
        - TOXENV=py37
        - PIP=pip3

addons:
  homebrew:
    packages:
    - python3

install:
  - $PIP install cython
  - $PIP install tox-travis

script: tox
